const vendors = [
    '../assets/vendors/abb.png',
    '../assets/vendors/acer.png',
    '../assets/vendors/alliedtelesis.png',
    '../assets/vendors/amd.png',
    '../assets/vendors/aoc.png',
    '../assets/vendors/aquarius.png',
    '../assets/vendors/asus.png',
    '../assets/vendors/aten.png',
    '../assets/vendors/avision.png',
    '../assets/vendors/benq.png',
    '../assets/vendors/brother.png',
    '../assets/vendors/canon.png',
    '../assets/vendors/cabeus.png',
    '../assets/vendors/chiq.png',
    '../assets/vendors/cisco.png',
    '../assets/vendors/crucial.png',
    '../assets/vendors/cyberPower.png',
    '../assets/vendors/dahua.png',
    '../assets/vendors/datalogic.png',
    '../assets/vendors/dell.png',
    '../assets/vendors/digma.png',
    '../assets/vendors/dkc.png',
    '../assets/vendors/d-link.png',
    '../assets/vendors/eaton.png',
    '../assets/vendors/eltex.png',
    '../assets/vendors/epson.png',
    '../assets/vendors/fsp.png',
    '../assets/vendors/fujitsu.png',
    '../assets/vendors/gAndG.png',
    '../assets/vendors/geleos.jpg',
    '../assets/vendors/gigabyte.png',
    '../assets/vendors/graviton.png',
    '../assets/vendors/hikvision.png',
    '../assets/vendors/hiper.png',
    '../assets/vendors/hitachi.png',
    '../assets/vendors/honeywell.png',
    '../assets/vendors/huawei.png',
    '../assets/vendors/Hynix.png',
    '../assets/vendors/hyperline.png',
    '../assets/vendors/ibm.png',
    '../assets/vendors/infortrent.png',
    '../assets/vendors/intel2.png',
    '../assets/vendors/ippon-logo.png',
    '../assets/vendors/irbis.png',
    '../assets/vendors/iru.png',
    '../assets/vendors/jabra_logo.gif',
    '../assets/vendors/katusha.png',
    '../assets/vendors/kingston.png',
    '../assets/vendors/konicaMinolta.png',
    '../assets/vendors/kramer.png',
    '../assets/vendors/kyocera.png',
    '../assets/vendors/lanmaster.png',
    '../assets/vendors/legrand.png',
    '../assets/vendors/lenovo_new.png',
    '../assets/vendors/lexmark.png',
    '../assets/vendors/LOGITECH.png',
    '../assets/vendors/machenike.png',
    '../assets/vendors/mikrotik.png',
    '../assets/vendors/msi.png',
    '../assets/vendors/nerpa.png',
    '../assets/vendors/netapp.png',
    '../assets/vendors/Panasonic.png',
    '../assets/vendors/pantum.png',
    '../assets/vendors/parus_electro.png',
    '../assets/vendors/patriot_logo.png',
    '../assets/vendors/plantronics.png',
    '../assets/vendors/powercube.png',
    '../assets/vendors/prestigio.png',
    '../assets/vendors/Qnap.png',
    '../assets/vendors/ricoh.gif',
    '../assets/vendors/rikor.png',
    '../assets/vendors/schneider.png',
    '../assets/vendors/seagate.png',
    '../assets/vendors/sharp.gif',
    '../assets/vendors/sony.png',
    '../assets/vendors/SuperMicro_Computer.png',
    '../assets/vendors/tplink.png',
    '../assets/vendors/trueconf.jpg',
    '../assets/vendors/utinet.png',
    '../assets/vendors/valday.png',
    '../assets/vendors/vestel.png',
    '../assets/vendors/viewsonic.png',
    '../assets/vendors/yadro.png',
    '../assets/vendors/yealink.png',
    '../assets/vendors/zebra.png',
    '../assets/vendors/zyxel.png',
]

const vendorsList = document.querySelector('.vendors__list');

function createItem (el) {
  let item = document.createElement('li');
  item.classList.add('vendors_item');
  item.style.backgroundImage = el;
  item.innerHTML = `<img class='vendors__item_image' src=${el} alt='Название вендора'>`;
  document.querySelector('.vendors__list').appendChild(item);
}

vendors.map(el => createItem(el));